# Generated by Django 4.2.30 on 2026-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='antonyms',
            field=models.CharField(blank=True, help_text='Comma-separated antonyms.', max_length=255),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('pronoun', 'Pronoun'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection')], max_length=20),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='synonyms',
            field=models.CharField(blank=True, help_text='Comma-separated synonyms.', max_length=255),
        ),
    ]
