# Generated by Django 4.2.30 on 2026-10-06 06:31

from django.db import migrations, models
import django.db.models.deletion


def create_default_segment_and_backfill(apps, schema_editor):
    Segment = apps.get_model('learning', 'Segment')
    Lesson = apps.get_model('learning', 'Lesson')

    default_segment, _ = Segment.objects.get_or_create(
        name='Others',
        defaults={'description': 'Uncategorized bundles.'},
    )
    Lesson.objects.filter(segment__isnull=True).update(segment=default_segment)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_segment_lesson_segment'),
    ]

    operations = [
        migrations.RunPython(create_default_segment_and_backfill, noop_reverse),
        migrations.AlterField(
            model_name='lesson',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundles', to='learning.segment'),
        ),
    ]
