# Generated by Django 4.2.30 on 2026-10-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_synonym_antonym_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free-preview bundles can be browsed without logging in.'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('learning', 'Lesson').objects.filter(serial=1).update(is_free=True),
            lambda apps, schema_editor: None,
        ),
    ]
