# Generated by Django 4.2.30 on 2026-10-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0007_add_bundle_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='learning.vocabulary')),
            ],
            options={
                'ordering': ['-learned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wordprogress',
            constraint=models.UniqueConstraint(fields=('user', 'vocabulary'), name='unique_user_word_progress'),
        ),
    ]
